global:
  storageClass: bahmni-efs-sc
  nodeSelector:
    eks.amazonaws.com/nodegroup: nonprod

metadata:
  labels:
    environment: dev
  ingress:
    PROXY_BODY_SIZE: "7m"
    ABDM_PROXY_BODY_SIZE: "30m"

openmrs:
  enabled: true
  metadata:
    labels:
      environment: dev
  image:
    tag: profiling
  config:
    OMRS_JAVA_SERVER_OPTS: '-Dfile.encoding=UTF-8 -server -Xms1024m -Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=25 -XX:G1MaxNewSizePercent=50 -XX:SurvivorRatio=8 -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:CompressedClassSpaceSize=256m -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./java.hprof -Xloggc:/usr/local/tomcat/logs/gc.log -XX:+UseStringDeduplication -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -agentpath:/etc/profiling/YourKit-JavaProfiler-2022.9/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all -javaagent:/etc/jvm_metrics/jmx_prometheus_javaagent.jar=8280:/etc/jvm_metrics/config.yml'
    OMRS_JAVA_MEMORY_OPTS: ''
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: true
crater:
  enabled: true
  config:
    AUTO_INSTALL: "true"
    ADMIN_NAME: Super Man
    COMPANY_NAME: Bahmni
    COMPANY_SLUG: bahmni
    COUNTRY_ID: 101
  secrets:
    ADMIN_EMAIL: "superman@bahmni.org"
reports:
  enabled: true
  config:
    OPENMRS_HOST: "openmrs"
hiu:
  enabled: true
  config:
    POSTGRES_HOST: "bahmni-dev-postgresql"
    RABBITMQ_HOST: "bahmni-dev-rabbitmq"
    HIU_ID: "Bahmni"
    HIU_NAME: "Bahmni"

hiu-db:
  enabled: true
  config:
    JAVA_TOOL_OPTIONS: "-Djdbc.url=jdbc:postgresql://bahmni-dev-postgresql:5432/ -Djdbc.username=postgres -Djdbc.password=welcome -Djdbc.database=health_information_user"
hiu-ui:
  enabled: true
  config:
    POSTGRES_HOST: bahmni-dev-postgresql
    RABBITMQ_HOST: bahmni-dev-rabbitmq
hip:
  enabled: true
  config:
    CONNECTION_STRING: "Host=bahmni-dev-postgresql;Port=5432;Username=postgres;Password=welcome;Database=hipservice"
    RABBITMQ_HOST: "bahmni-dev-rabbitmq"
    BAHMNI_ID: "Bahmni"
otp-service:
  enabled: true
hip-atomfeed:
  enabled: true

postgresql:
  enabled: true
  volumePermissions:
    enabled: true
  primary:
    persistence:
      subPath: dev
      storageClass: bahmni-efs-sc
      accessModes:
        - ReadWriteMany
    nodeSelector:
      eks.amazonaws.com/nodegroup: nonprod
  image:
    tag: 14-debian-11

rabbitmq:
  enabled: true
  auth:
    erlangCookie: bahmni
  persistence:
    storageClass: bahmni-efs-sc
    accessModes:
      - ReadWriteMany
  nodeSelector:
    eks.amazonaws.com/nodegroup: nonprod
  image:
    repository: rabbitmq
    tag: alpine

patient-documents:
  enabled: true
  config:
    OPENMRS_HOST: "openmrs"

crater-atomfeed:
  enabled: true
  metadata:
    labels:
      environment: dev
appointments:
  enabled: true

implementer-interface:
  enabled: true

abha-verification:
  enabled: true

bahmni-metabase:
  enabled: true
  config:
    MB_DB_TYPE: postgres
    MB_DB_DBNAME: 'metabase'
    MB_DB_PORT:  5432
    MART_DB_NAME: martdb
  secrets:
    MB_ADMIN_FIRST_NAME: 'Admin'
    MB_DB_HOST: 'bahmni-dev-postgresql'
    MART_DB_HOST: 'bahmni-dev-postgresql'

bahmni-mart:
  enabled: true
  config:
    MART_DB_NAME: martdb
  secrets:
    MART_DB_HOST: "bahmni-dev-postgresql"
