metadata:
  labels:
    environment: dev

openmrs:
  enabled: true
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: true
crater:
  enabled: true
reports:
  enabled: false
  config:
    OPENMRS_HOST: "bahmni-openmrs"
hiu:
  enabled: false
hiu-db:
  enabled: false
hiu-ui:
  enabled: false
hip:
  enabled: false
otp-service:
  enabled: false
abdm-db:
  enabled: false
rabbit-mq:
  enabled: false

rabbitmq:
  auth:
    username: guest
    password: guest
    erlangCookie: guest

global:
  postgresql:
    auth:
      postgresPassword: welcome