metadata:
  labels:
    environment: dev

openmrs:
  enabled: true
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: true
crater:
  enabled: true
reports:
  enabled: true
  config:
    OPENMRS_HOST: "bahmni-openmrs"
hiu:
  enabled: false
hiu-db:
  enabled: true
hiu-ui:
  enabled: true
hip:
  enabled: false
otp-service:
  enabled: true
abdm-db:
  enabled: true
rabbit-mq:
  enabled: true

rabbitmq:
  auth:
    username: bahmni
    password: bahmni
    erlangCookie: bahmni

global:
  postgresql:
    auth:
      postgresPassword: welcome