apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  # name: bahmni-aws-ingress-class
  name: bahmni-nginx-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true'
spec:
  # controller: ingress.k8s.aws/alb
  controller: k8s.io/ingress-nginx
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bahmni-ingress
  labels:
    environment: {{ .Values.metadata.labels.environment }}
  annotations:
  # enable to use secure backend
    # nginx.ingress.kubernetes.io/secure-backends: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if index .Values "bahmni-web" "enabled" }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bahmni-web
                port:
                  number: 8091
          {{- end }}

          {{- if .Values.openmrs.enabled }}
          - path: /openmrs
            pathType: Prefix
            backend:
              service:
                name: bahmni-openmrs
                port:
                  number: 8080
          {{- end }}

          {{- if index .Values "bahmni-lab" "enabled" }}
          - path: /lab
            pathType: Prefix
            backend:
              service:
                name: bahmni-lab
                port:
                  number: 8090
          {{- end }}

    - host: payments-{{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.crater.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crater-nginx
                port:
                  number: 80
          {{- end }}
